//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceView
    {
        public string name { get; set; }
        public string img { get; set; }
        public int price { get; set; }
        public int pkID { get; set; }
        public int factorNumber { get; set; }
        public int fkProduct { get; set; }
        public int fkCostumer { get; set; }
        public bool status { get; set; }
        public string transID { get; set; }
        public string trackingID { get; set; }
        public string cardNumber { get; set; }
    }
}
