//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineShopProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineShop : DbContext
    {
        public onlineShop()
            : base("name=onlineShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoryTbl> categoryTbls { get; set; }
        public virtual DbSet<ProductsTbl> ProductsTbls { get; set; }
        public virtual DbSet<CostumersTbl> CostumersTbls { get; set; }
        public virtual DbSet<invoiceTbl> invoiceTbls { get; set; }
        public virtual DbSet<invoiceView> invoiceViews { get; set; }
    }
}
